spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/taxi"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ea
    password: cs544
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect

server:
  port: 8090
  servlet:
    context-path: "/api/v1"

mail:
  host: smtp.gmail.com
  port: 587
  username: rmkaheto@gmail.com
  password: xgvluxvbylcmgrym
  protocol: smtp
  tls: true
  properties.mail.smtp:
    auth: true
    starttls.enable: true
    ssl.trust: smtp.gmail.com
  debug: true
#mail:
#  smpt:
#    auth: true
#    server: smtp.gmail.com
#      username: "rmkaheto@gmail.com"
#      password: xgvluxvbylcmgrym
#    port: 587
#    starttls:
#      enable: true
#  transport:
#    protocol: smtp
#  debug: true

#hibernate:
#  dialect: org.hibernate.spatial.dialect.mysql.MySQL56SpatialDialect
