spring:
  application:
    name: Taxi24
  datasource:
    url: "jdbc:mysql://localhost:3306/taxi24"
#    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ea
    password: cs544
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
  twilio:
    accountSid: your_account_sid
    authToken: your_auth_token
    phoneNumber: your_twilio_phone_number

server:
  port: 8090
  servlet:
    context-path: "/api/v1"

mail:
  host: smtp.gmail.com
  port: 587
  username: taxzitwentyfour@gmail.com
  password: qjcdmkeuqegedoif
  protocol: smtp
  tls: true
  properties.mail.smtp:
    auth: true
    starttls.enable: true
    ssl.trust: smtp.gmail.com
  debug: true

msgs:
  registrations:
    subject: "Taxi24 Registration Confirmation"
    welcome: "Hello %s, we’re excited to have you. Wherever you’re going, requesting a ride is just a tap away, Thank you for registering with Taxi24."